version: '3.2'

services:
  api: 
    build: './api'
    expose:
      - "5000"
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: test
  db_admin:
    image: adminer
    ports:
      - 8080:8080
  web_scraper:
    build: './web_scraper'
